# Generated by Django 5.1.2 on 2024-11-03 23:06

import django.contrib.auth.models
import recipesapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_num', models.PositiveIntegerField(verbose_name='Порядковый номер шага')),
                ('description', models.TextField(verbose_name='Описание шага')),
                ('image', models.ImageField(default='1', upload_to='images/', verbose_name='Изображение шага')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название блюда')),
                ('description', models.TextField(verbose_name='Краткое описание рецепта')),
                ('cooking_time', models.CharField(max_length=20, verbose_name='Время приготовления блюда')),
                ('image', models.ImageField(default='2', upload_to='images/', verbose_name='Изображение блюда')),
                ('recipe_category', models.IntegerField(verbose_name=recipesapp.models.Category)),
                ('author', models.IntegerField(verbose_name=django.contrib.auth.models.User)),
                ('products', models.ManyToManyField(to='recipesapp.product', verbose_name='Продукты')),
                ('cooking_steps', models.ManyToManyField(to='recipesapp.steps', verbose_name='Шаги')),
            ],
        ),
    ]
