# Generated by Django 5.1.2 on 2024-11-16 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0003_alter_recipe_image_alter_recipe_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipesapp.category', verbose_name='Категория рецепта'),
        ),
    ]
