# Generated by Django 5.1.2 on 2024-11-16 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0004_alter_recipe_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='products',
        ),
    ]
