# Generated by Django 5.1.2 on 2024-11-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0007_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Изображение блюда'),
        ),
    ]
